apiVersion: v1
kind: Secret
metadata:
  name: go-service-starter-secrets
  namespace: go-service-starter
  labels:
    app.kubernetes.io/name: go-service-starter
    app.kubernetes.io/part-of: go-service-starter
type: Opaque
stringData:
  DATABASE_URL: postgres://replace-me:replace-me@postgres.example.com:5432/go_service_starter?sslmode=require
